// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `split_pos`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Loads the Sudachi dictionary and prepares the tokenizer for `tokenize`
/// calls. Must be called once before `tokenize`; safe to call more than
/// once -- a call after successful initialization is a no-op success, so
/// app-startup code and test setup can call it unconditionally without
/// coordinating who calls it first.
///
/// `resource_dir` must contain `char.def`, `unk.def`, and `rewrite.def`
/// (sudachi.rs's own repo ships these under its top-level `resources/`).
/// `dictionary_path` is the path to a SudachiDict `.dic` file (e.g.
/// `system_small.dic`). Resolving these paths to wherever the app actually
/// bundles/downloads the dictionary is a follow-up -- see
/// docs/research/r4-tokenizer.md §3 and §6; this pass only makes the paths
/// injectable.
Future<void> initTokenizer({
  required String resourceDir,
  required String dictionaryPath,
}) => RustLib.instance.api.crateApiInitTokenizer(
  resourceDir: resourceDir,
  dictionaryPath: dictionaryPath,
);

/// Tokenize Japanese text and return one `TokenInfo` per morpheme, in
/// order. Requires `init_tokenizer` to have completed first, or returns
/// `TokenizerError::NotInitialized`.
Future<List<TokenInfo>> tokenize({required String text}) =>
    RustLib.instance.api.crateApiTokenize(text: text);

/// One Sudachi morpheme, shaped to match the L2-derived subset of
/// `lib/core/models/token.dart`'s `Token` fields -- everything a
/// `Tokenizer` populates (surface/dictForm/reading/pos/inflection). See
/// `lib/l2_linguistics/tokenizer/tokenizer.dart` for the Dart-side
/// contract this feeds.
class TokenInfo {
  final String surface;
  final String dictForm;
  final String reading;
  final String pos;

  /// Conjugation type + conjugated form (e.g. "下一段-バ行,連用形-一般"),
  /// or `None` for non-inflecting words (particles, nouns, ...). See
  /// `split_pos`.
  final String? inflection;

  const TokenInfo({
    required this.surface,
    required this.dictForm,
    required this.reading,
    required this.pos,
    this.inflection,
  });

  @override
  int get hashCode =>
      surface.hashCode ^
      dictForm.hashCode ^
      reading.hashCode ^
      pos.hashCode ^
      inflection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenInfo &&
          runtimeType == other.runtimeType &&
          surface == other.surface &&
          dictForm == other.dictForm &&
          reading == other.reading &&
          pos == other.pos &&
          inflection == other.inflection;
}

@freezed
sealed class TokenizerError with _$TokenizerError implements FrbException {
  const TokenizerError._();

  /// The dictionary or its resource files (char.def/unk.def/rewrite.def)
  /// failed to load from the given paths -- e.g. wrong path, missing
  /// file, or a corrupt/incompatible dictionary.
  const factory TokenizerError.dictionaryLoad(String field0) =
      TokenizerError_DictionaryLoad;

  /// A Sudachi tokenization call itself failed. Rare in practice --
  /// Sudachi's tokenizer is total over any `&str` input -- but Sudachi's
  /// own API is fallible (e.g. pathological OOV/plugin errors), so this
  /// is surfaced rather than unwrapped.
  const factory TokenizerError.tokenization(String field0) =
      TokenizerError_Tokenization;

  /// `tokenize` was called before `init_tokenizer` completed
  /// successfully.
  const factory TokenizerError.notInitialized() = TokenizerError_NotInitialized;
}
