// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_tokenizer`

/// Tokenize Japanese text and return one `TokenInfo` per morpheme, in order.
/// This is the exact function `flutter_rust_bridge_codegen` generates a Dart
/// binding for in this spike.
Future<List<TokenInfo>> tokenize({required String text}) =>
    RustLib.instance.api.crateApiTokenize(text: text);

/// Mirrors the subset of `lib/core/models/token.dart`'s `Token` fields that
/// come from L2/Sudachi (i.e. everything except `surface` there is null
/// until this runs). `pos` is flattened to a comma-joined string here only
/// because wiring a `Vec<String>` through flutter_rust_bridge is exactly as
/// easy -- it was left a string purely so the printed spike output stays
/// readable; a real binding would return `Vec<String>` untouched.
class TokenInfo {
  final String surface;
  final String dictForm;
  final String reading;
  final String pos;

  const TokenInfo({
    required this.surface,
    required this.dictForm,
    required this.reading,
    required this.pos,
  });

  @override
  int get hashCode =>
      surface.hashCode ^ dictForm.hashCode ^ reading.hashCode ^ pos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenInfo &&
          runtimeType == other.runtimeType &&
          surface == other.surface &&
          dictForm == other.dictForm &&
          reading == other.reading &&
          pos == other.pos;
}
